import type { Metadata } from "next";
import { Providers } from "./providers";
import { Header } from "@/components/header";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="w-full min-h-dvh grid grid-rows-[max-content_1fr] px-2 md:px-4">
            <Header />
            <div className="flex items-center md:items-start justify-center h-full">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
